### ISSUE TITLE
option value is overwritten by label when value is nullable

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#11]
found using `transform` into a custom type

```yaml
- ...
  options:
    - label: Empty value
      value: null
```
See https://github.com/andersonba/yve-bot/blob/master/src/ui/ui.ts#L47

**Result:** "Empty value"
**Expected:** `null`
