### ISSUE TITLE
feature: support for textarea using multiline prop

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#111]
Use `textarea` when multiline is enabled, otherwise, keeping the `input[type=text]`.

In `textarea` case, submit the message typing `Enter` and break line using `Shift+Enter`.

Input type: `boolean`
Default value: `true` (opt-out)

### Usage

```yaml
- message: Type a message (use Shift+Enter to break line)
  type: String

- message: Type your name
  type: String
  multiline: false
```
