### ISSUE TITLE
fix jumping using "flow:name"

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#137]
**Example**
```yaml
- flow: introduction
  rules:
    - next: "flow:identify"

- flow: identify
  rules:
    - Your name?
```

**Expected**
Jump to first rule of flow "identify"
