### ISSUE TITLE
support for rules without messages

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#138]
Sometimes we want send options buttons to the user without a message.

**Example**
```yaml
- type: SingleChoice
  options:
    - Blue
    - Red
```

**Expected**
Show the buttons to the user when type is `SingleChoice` or `MultipleChoice`
