### ISSUE TITLE
missing "string way" of preActions and postActions

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#139]
Currently, only `actions` can receive the string way value

**Example**
```yaml
- actions:
  - timeout: 2000
  - pushNotification  # string way
```

**Expected**
Replicate this feature to `preActions` and `postActions`.
