### ISSUE TITLE
compiled messages in (pre/post)actions value

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#140]
Use `output` data to compile actions value.

**Example**
```yaml
- message: Enter the email
  name: email
  type: String
  postActions:
    - sendWelcomeEmail: "{email}"

- actions
  - registerNewsletter: "{email}"
```
