### ISSUE TITLE
feature: run actions defined in options

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#165]
Sometimes we need to run actions after the user chooses some options.

Example:

```yaml
- message: How do you want receive news?
  type: MultipleChoice
  options:
    - label: E-mail
      postActions:
        - setNewsletterMethod: email
    - label: SMS
      postActions:
        - setNewsletterMethod: sms
```
