### ISSUE TITLE
Skip doesn't accept boolean type

### ISSUE THREAD

**Issue by gabrielpeixoto** [andersonba/yve-bot#176]
Example:
```
- Hello! I'm Yve Bot.

- message: What's your name?
  name: name
  type: String
  replyMessage: Thanks for the answer, {name}!
  validators:
  - min: 4
  - minWords: 1

- message: What city do you live in?
  name: city
  multiline: false
  type: String

- message: I'll skip this message
  skip: true

- message: Thanks, wait a moment.
```

The message _"I'll skip this message"_ won't appear. OK.

Example 2:
```
- Hello! I'm Yve Bot.

- message: What's your name?
  name: name
  type: String
  replyMessage: Thanks for the answer, {name}!
  validators:
  - min: 4
  - minWords: 1

- message: What city do you live in?
  name: city
  multiline: false
  type: String

- message: I'll skip this message
  skip: false

- message: Thanks, wait a moment.
```

The message _"I'll skip this message"_ won't appear. not OK, because I don't want to skip the message.

But if the value of _skip_ is a function, it works normally. Example 3:
```
- Hello! I'm Yve Bot.

- message: What's your name?
  name: name
  type: String
  replyMessage: Thanks for the answer, {name}!
  validators:
  - min: 4
  - minWords: 1

- message: What city do you live in?
  name: city
  multiline: false
  type: String

- message: I'll skip this message
  skip: !!js/function >
    function skip(output, rule, bot) {
      return false;
    }

- message: Thanks, wait a moment.
```

The Example 3 is OK, show the message _"I'll skip this message"_
