### ISSUE TITLE
After ending chat

### ISSUE THREAD

**Issue by kofdasad** [andersonba/yve-bot#196]
Hi Again!

Sorry, i don't know if this goes here, but i think this something like an enhancement.
what happen when chat ends?

it completely stops, and let the user input open without further answers...

![image](https://user-images.githubusercontent.com/7155029/106924899-8e87c480-66dd-11eb-8c24-1af7b09952c5.png)

there's a way to make the passive mode to read any character redirect the user to new rule?

for example...

user type:
       "sorry, i have more questions"
Bot:
       "let me help you with that, choose what do you need"
       op1 - op2 - op 3
       
I know we can use passive, but is hard to catch all words

Thank  you

**Comment by andersonba** [comment]
Hi again! 😄 

> it completely stops, and let the user input open without further answers...

Weird.. it should redirect you to another page ([commit](https://github.com/andersonba/yve-bot/commit/33936bbc7e73a288e01e1e2202b3e5f94244d3ec) maybe fix it, let's see.. thanks)

> there's a way to make the passive mode to read any character redirect the user to new rule?

Are you referring when the chat ends? For any character takes the user to a specific rule?
If yes, you can just use `Any` type, like below:

```yaml
- message: Bye!
  type: Any
- message: let me help you with that, choose what do you need
  type: SingleChoice
  options:
    - op1
    - op2
    - op3
```
