### ISSUE TITLE
CLI throws exception when simplechoice is not a number.

### ISSUE THREAD

**Issue by mfandre** [andersonba/yve-bot#267]
CLI throws exception when singlechoice is not a number. What the possibility to redo the question until the user not selected a correct value.

rules:
```
- message: Hello!
- message: Enter your e-mail
  type: String
  name: email
- message: Choose a number
  name: number
  type: SingleChoice
  options:
    - label: One
      value: 1
    - label: Two
      value: 2
  replyMessage: You chose number {number.label} (the same of {number})
```

Example:
```
Hello!
Enter your e-mail
You:  asdasd
Choose a number
Choose an option: [1, 2]
You:  asdasd
/Users/andre.ferraz/_projetos/MY/Agendinha/node_modules/yve-bot/core.js:850
                                                (t.toString = function () {
                                                            ^

TypeError: Cannot set properties of undefined (setting 'toString')
    at /Users/andre.ferraz/_projetos/MY/Agendinha/node_modules/yve-bot/core.js:850:61
    at /Users/andre.ferraz/_projetos/MY/Agendinha/node_modules/yve-bot/core.js:855:43
    at Array.map (<anonymous>)
    at zt.<anonymous> (/Users/andre.ferraz/_projetos/MY/Agendinha/node_modules/yve-bot/core.js:823:35)
    at /Users/andre.ferraz/_projetos/MY/Agendinha/node_modules/yve-bot/core.js:130:35
    at Object.next (/Users/andre.ferraz/_projetos/MY/Agendinha/node_modules/yve-bot/core.js:138:19)
    at r (/Users/andre.ferraz/_projetos/MY/Agendinha/node_modules/yve-bot/core.js:41:25)
```
