### ISSUE TITLE
Custom validator is not working, could you provide an example?

### ISSUE THREAD

**Issue by yasinAtlibra** [andersonba/yve-bot#30]
I was trying to define an customer validator to check user's answer. If the answer is "yes","sure" ... then jump to one rule. Otherwise, terminate (which part I did not write yet). 
Here is my code.

          bot.start();

         bot.validators.define("agreed", {
          validate: (expected, answer) => {
              console.log("answer:"answer)
              console.log("expected:"expected)
              return answer === "yes" || answer === "sure";
           },
              warning: "You disagree :( sorry!"
         });

The rules are as following.

            - message: How can I help you?
              name: hello
             type: String
             next: order
            

            - message: would like to order something?!
             name: order
             type: String
             -validators : 
                 - agreed : true
                   next: food

            - message: what do you like to have?

It works without that validator. I tried to print out inside the definition of validator, but nothing is printed. 

Am I defining validator incorrectly?
Could you provide an example of validator or tell me what I am doing wrong here?

Thanks in advance!

**Comment by andersonba** [comment]
Your YAML example is invalid.
Check using a [linter](http://www.yamllint.com).

I have tested it with the following code:
```yaml
- message: How can I help you?
  name: hello
  type: String

- message: Would like to order something?!
  name: order
  type: String
  validators:
    - agreed: true

- message: What do you like to have?
  type: String
  name: product
```
It works correctly.

But you can use the `SingleChoice` type to make this question:
```yaml
- message: Would like to order something?!
  name: order
  type: SingleChoice
  options:
    - label: Yes
      next: products
    - label: No
      next: quit
```
