### ISSUE TITLE
synonyms support

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#32]
- Should receive a string (comma-separated)
- Should receive an array
- Should store the option.value in output instead of synonym

Expected:
```yaml
- ...
  type: SingleChoice
  options:
    - value: Yes
      synonyms: Yep, All right, Okay
    - value: No
      synonyms:
        - Bye
        - Really?
```
```
> bot: Yes or no?
> user: yep
// store: { confirmation: "Yes" }
