### ISSUE TITLE
feature: grouping rules into flows

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#40]
**Group rules using flow concept.**
The flow is not mandatory for rule specification.
It's just an optional feature to organize the bot conversations and prepare for next feature: **Add new rules at runtime.**

### Defining a flow
```yaml
- flow: flow_name
  rules:
    - List of rules
    - message: ...

# or

- message: List of rules
  flow: flow_name

- message: ...
  flow: flow_name
```

### Jumping between flows
```yaml
- flow: identification
  rules:
    - Welcome!
    - message: Your name?
      name: name
      type: String
    - message: Thanks!
      next: question.help
    - Skip

- flow: question
  rules:
    - message: Can I help you?
      name: help

# bot> Welcome!
# bot> Your name?
# usr> Anderson
# bot> Thanks
# bot> Can I help you?
```

### Jumping inside flow
Keeping currently behavior
```yaml
- flow: default
  rules:
    - message: Welcome
      next: end
    - message: Skip
    - message: End
      name: end
      exit: true

- flow: another
  rules:
    - Skip 2
    - message: Skip 3
      name: end

# bot> Welcome
# bot> End
```
