### ISSUE TITLE
Invalid format for validator with regex

### ISSUE THREAD

**Issue by tupy** [andersonba/yve-bot#51]
Validator fails when the input is an integer, such as `7192689343`.

```yaml
    - message: Type your phone number. (with DDD)
      name: phone
      type: String
      validators:
        - regex: ^\(?\d{2}\)?\s?\d{4,5}[\.-\s]?\d{4}$
```
