### ISSUE TITLE
Option's limitation for Multiple/Single choices fields

### ISSUE THREAD

**Issue by rafaelverger** [andersonba/yve-bot#59]
Should be possible to limit how many options are shown to users in the list of Single/MultipleChoice fields.

*Suggestion:*
```yaml
rule:
  - type: MultipleChoice
  - maxOptions: 3
  - options:
    - label: option1
    - label: option2
    - label: option3
    - label: option4
    - label: option5
```

Would show options 1,2 and the third one would be `More options` that would show the other options 3, 4 and 5.
