### ISSUE TITLE
single/multiple-choices: support for compile message with option label

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#6]
```yaml
- name: colors
  options:
    - label: Black
      value: '#000'
    - label: White
      value: '#FFF'
 
- message: {{colors}} are colors
```

Result:
```
#000,#FFF are colors
```

Expected:
```
Black,White are colors
```

**Comment by andersonba** [comment]
**SingleChoice usage**
```yaml
  ...
  options:
    - label: Black
      value: #000
    - label: White
      value: #fff
```
```
{{ color }} or {{ color.value }}
#000

{{ color.label }}
Black
```

**MultipleChoice usage**
```yaml
  ...
  options:
    - label: One
      value: 1
    - label: Two
      value: 2
```
```
{{ numbers }}
1,2

{{ numbers.0.label }}
One

{{ numbers.0 }} or {{ numbers.0.value }}
1
```
