### ISSUE TITLE
choose actions/validators using array of string [yaml]

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#60]
Currently
```yaml
- type: name
  actions:
    - action1: true
    - action2: true
```

Suggested
```yaml
- type: name
  actions:
    - action1  # assumes true
    - action2
    - action3:
      prop1: value
      ...
```
