### ISSUE TITLE
inherited delay in replyMessage

### ISSUE THREAD

**Issue by andersonba** [andersonba/yve-bot#71]
```yaml
- message: Hello
  delay: 1234
  replyMessage: Thanks
```

Types "Thanks" with delay defined in rule: `1234` or gets the default defined in yvebot options.
